# Global settings
replicaCount: 1

backend:
  image:
    repository: docksaif/scent-luxe-backend
    tag: "v2"
  service:
    port: 8081

frontend:
  image:
    repository: docksaif/scent-luxe-frontend
    tag: "v3"
  service:
    port: 80

database:
  password: "password"
  storageSize: "1Gi"

ingress:
  enabled: true
  host: "scentluxe.local"